services:
  h2db:
    image: oscarfonts/h2:latest
    container_name: petcenter-h2db
    restart: unless-stopped
    ports:
      - "81:81"
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - h2-data:/opt/h2-data

  app:
    build: .
    container_name: petcenter-api
    restart: unless-stopped
    depends_on:
      - h2db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2db:1521/./petcenterdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: "true"

volumes:
  h2-data:
