spring.application.name=challengepetcenter

springdoc.info.title=API para acompanhamento do pet - PetCenter
springdoc.info.description=API para acompanhamento diario da saude e humor dos pets
springdoc.info.version=v1.0.0
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.try-it-out-enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/petcenterdb}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=${SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS:true}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
spring.jackson.default-property-inclusion=non_null
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
